# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

project_name: autotheme
env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - git-chglog -o CHANGELOG.md

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: "386" 
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser -X main.treeState={{ .IsGitDirty }}

universal_binaries:
  - replace: false

checksum:
  name_template: "checksums.txt"

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if eq .Arch "ppc64" }}le{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}

    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
    files:
      - src: README.md
        info:
          owner: root
          group: root
      - src: LICENSE
        info:
          owner: root
          group: root
      - src: CHANGELOG.md
        info:
          owner: root
          group: root

release:
  draft: true
  replace_existing_draft: true
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"
  make_latest: true