style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/damienbullis/autotheme
options:
  commit_groups:
    title_maps:
      feat:  "✨ Features"
      chore: "🛠️ Maintainance"
      bug:   "🐛 Bug Fixes"
    
  header:
    pattern: ^([a-zA-Z]+)\s*-\s*(.+)$
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE