style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/damienbullis/autotheme
options:
  commit_groups:
    title_maps:
      sparkles: ✨ Features
      bug: 🐛 Bugs
      zap: ⚡ Performance 
      recycle: ♻️ Improvements
  header:
    pattern: "^:(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE