style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/damienbullis/autotheme
options:
  commit_groups:
    title_maps:
      feat: ✨ Features
      fix: 🐛 Fixes
      perf: ⚡ Performance 
      main: 🛠️ Maintainance
      bug: 🐛 Fixes
    
  header:
    pattern: "^(\\w*)\\ - \\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE